import {
  Baby,
  Banknote,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Camera,
  Car,
  Dumbbell,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  MapPinned,
  Music,
  PartyPopper,
  PiggyBank,
  Plane,
  Shield,
  Shirt,
  ShoppingBag,
  Sofa,
  Sparkles,
  Sprout,
  Smartphone,
  Train,
  Umbrella,
  Utensils,
  WalletCards,
  Wrench,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

export const iconOptions: Array<{
  name: string
  icon: LucideIcon
}> = [
  { name: "Spaarpot", icon: PiggyBank },
  { name: "Geld", icon: Banknote },
  { name: "Rekening", icon: WalletCards },
  { name: "Bank", icon: Landmark },
  { name: "Vakantie", icon: Plane },
  { name: "Weekend", icon: MapPinned },
  { name: "Feest", icon: PartyPopper },
  { name: "Wonen", icon: Home },
  { name: "Interieur", icon: Sofa },
  { name: "Laptop", icon: Laptop },
  { name: "Telefoon", icon: Smartphone },
  { name: "Auto", icon: Car },
  { name: "Trein", icon: Train },
  { name: "Buffer", icon: Umbrella },
  { name: "Noodfonds", icon: Shield },
  { name: "Cadeau", icon: Gift },
  { name: "Gezin", icon: Heart },
  { name: "Kind", icon: Baby },
  { name: "Zorg", icon: HeartPulse },
  { name: "Studie", icon: GraduationCap },
  { name: "Boeken", icon: BookOpen },
  { name: "Fiets", icon: Bike },
  { name: "Werk", icon: BriefcaseBusiness },
  { name: "Kleding", icon: Shirt },
  { name: "Winkelen", icon: ShoppingBag },
  { name: "Eten", icon: Utensils },
  { name: "Sport", icon: Dumbbell },
  { name: "Game", icon: Gamepad2 },
  { name: "Muziek", icon: Music },
  { name: "Audio", icon: Headphones },
  { name: "Camera", icon: Camera },
  { name: "Sieraad", icon: Gem },
  { name: "Klussen", icon: Hammer },
  { name: "Onderhoud", icon: Wrench },
  { name: "Groei", icon: Sprout },
  { name: "Droom", icon: Sparkles },
]

export function getIconOption(iconName: string) {
  return (
    iconOptions.find((option) => option.name === iconName) ?? iconOptions[0]
  )
}
